# <% app_name = Rails.application.class.parent_name.underscore %>

development:
  adapter: postgresql
  database: teamup_development

test:
  adapter: postgresql
  database: <%= app_name %>_test

production:
  adapter: postgresql
  database: teamup_production
